twig:
<<<<<<< HEAD
=======
    form_themes: ['bootstrap_4_layout.html.twig']
>>>>>>> origin/omarfitouri
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
<<<<<<< HEAD
=======
    
>>>>>>> origin/omarfitouri
